### ISSUE TITLE
The Pragmatic Programmer, 20th Anniversary Edition: Chapters 2-3 – March 31st

### ISSUE THREAD

**Issue by lachlanhardy** [Blackmill/book-club#58] opened 2020-03-25 06:17 UTC
https://pragprog.com/book/tpp20/the-pragmatic-programmer-20th-anniversary-edition

Aiming to cover:

  - Chapter 2
    - Topics 12-15
  - Chapter 3
    - Topics 16-17

MC: @HashNotAdam  
Notes: @lachlanhardy 

See you 12 pm Tuesday, March 31st @ https://whereby.com/blackmill

Ping gday@blackmill.co if you want a calendar invite and access to the low-volume Slack beforehand.

**Comment by HashNotAdam** [comment] 2020-04-02 04:39
# Chapter 2—A Pragmatic Approach

## Topic 12—Tracer bullets

- When a feature has a lot of unknowns, rather that attempting to lock in a specification for every possible obstacle, build this area first
- Find areas of uncertainty and produce just enough code to prove it can work
- This could involve writing "just enough code" in many layers of an application until the whole request works in some small way

> Tracer code is not disposable: you write it for keeps. It contains all the error checking, structuring, documentation, and self-checking that any piece of production code has. It simply is not fully functional.
>

Advantages:

- Users get to see something working early
- Developers build a structure to work in
- You have an integration platform
- You have a better feel for progress

### Traer bullets don't always hit their targets

> Tracer bullets show what you’re hitting. This may not always be the target. You then adjust your aim until they’re on target. That’s the point.
>

### Tracer code versus prototyping

- A prototype gets thrown away but tracer code is the foundation

## Topic 13—Prototypes and Post-it Notes

- Prototyping is a lot cheaper than full-scale production
- We build prototypes to expose risk and correct cheaply
- Prototypes don't need to use code (e.g. Post-It Notes and whiteboard drawings)
- If you can't build without all the details, maybe a Tracer Bullet is a better direction

### Things to prototype

- Prototype anything that carries risk, hasn't been tried before, is absolutely critical, or is unproven, experimental, or doubtful
- The value lies in the lessons learned, the code has no value

### How to use prototypes

Ignore:

- Correctness
- Completeness
- Robustness
- Style

> To prototype user interfaces, use a tool that lets you focus on the appearance and/or interactions without worrying about code
>

### Prototyping architecture

> What you are looking for is how the system hangs together as a whole... deferring details.
>

### How *not* to use prototypes

> Make it very clear that this code is disposable, incomplete, and unable to be completed
>

## Topic 14—Domain languages

- Computer languages influence how you think about a problem
- The language of the problem domain may also suggest a programming solution

### Characteristics of Domain Languages

- *Internal* domain languages are written in your host language (Ruby, Python, etc)
- *External* domain language are written in their own language and compiled into a form the host language can use

### Trade-offs between internal and external languages

- Internal domain langages get a lot of power for free but they are bound by the syntax and semantics of the host language
- External domain languages can have any synta you can write a parser for but it is a lot more work
- Writing a domain language adds cost; make sure it's worth it
- Use off-the-shelf external languages if you can
- Use external languages when your language will be written by the users of our application

## Topic 15—Estimating

> By learning to estimate, and by developing this skill to the point where you have an intuitive feel for the magnitudes of things, you will be able to show an apparent magical ability to determine their feasibility
>

- Estimate to avoid surprises

### How accurate is accurate enough?

- All answers are estimates
- Consider how much accuracy is necessary
- Try not to make the estimate sounce more accurate than it is (choose the units to reflect the accuracy you intend to convey)
- If the estimate is over 20 weeks, consider not giving it

### Where do estimates come from?

- Before coming up with an estimate, try to find someone who's done it before and find out how their problem was solved

### Understand what's being asked

- Grasp the scope of the domain

> Assuming there are no traffic accidents and there’s gas in the car, I should be there in 20 minutes.
>

### Build a model of the system

- Build a rough-and-ready bare-bones mental model
- Building the model leads to discoveries of underlying patterns and processes
- Possibly reexamine the request to suggest a simplier build
- Doubling the effort on the model may give you only a slight increase in accuracy

### Break the model into components

### Give each parameter a value

- Focus on finding the parameters that have the most impact on the result and concentrate on getting them about right
- Have a justifiable way of calculating critical parameters

### Calculate the answers

- In simple cases, a single estimate will do
- As systems get complex, hedge your answers
- You might get answers that seem strange; it's possible your understanding of the problem or model is wrong so don't dismiss them

#### Keep track of your estimating prowess

- Record your estimates
- Review how close your estimates were
- If it was wrong, find out why

### Estimating project schedules

Techniques for reducing estimate uncertainty

#### Painting the missile

- Estimates should be given with a range of scenarios
- Program Evaluation Review Technique (PERT)
  - Every PERT task has an optimistic and pessimistic estimate
  - A range helps avoid errors from padding due to uncertainty
  - Often PERT gives people a greater level of certainty than is justified

#### Eating the elephant

> Often the only way to determine the timetable for a project is by gaining experience on that same project
>

- Practice incremental development:
  - Check requirements
  - Analyze risk (and prioritize riskiest items earlier)
  - Design, implement, integrate
  - Validate with the users
- Initially, try not to nail down the number of iterations; this is likely just a guess
- Upon completion of an iteration, you can refine the expected number of iterations
- This may not be popular with management

#### What to say when asked for an estimate

> I'll get back to you

# Chapter 3—The basic tools

- Always be on the lookout for tools that could better suit your situation
- Let need drive your acquisitions

## Topic 16—The power of plain text

- The best format for storing knowledge persistently is plain text
- With binary formats, the context is separate from the data

### The power of text

- Plain text doesn't mean unstructured

#### Insurance against obsolescence

- Human-readable forms of data will outlive all other data
- You can parse a plain text file with only partial knowledge of its format
- There is a difference between human-readable and human-understandable

#### Leverage

- Virtually every tool in the computing universe can operate on plain text
- Plain text can be version controlled with version diffs

#### Easier testing

- Simplier to add, update, or modify test data

### Lowest Common Denominator

- The advantages can outweigh all the drawbacks
- All parties need to communicate using a common stand and plain text is standard

## Topic 17—Shell games

- A programmer's workbench is the command shell

> From the shell prompt, you can invoke your full repertoire of tools, using pipes to combine them in ways never dreamt of by their original developers”
>

- For programmers raised on GUIs, this might seem extreme
- GUIs are wonderful but avoiding the shell limits capability
- What you see is what you get but what you see is all you get

> Gain familiarity with the shell, and you’ll find your productivity soaring
>

### A shell of your own

- A developer should customise their shell
  - Set colour themes
  - Configue a prompt
  - Add aliases and shell functions
  - Customise command completion

## Topic 18—Power editing

- Tools are the extension of your hand and you need to be able to manuplulate text as effortlessly as possible
- Achieving editor fluency allows you to stop thinking about the mechanics of editing and focus on programming

### Moving toward fluency

- Learn the commands that make your life easier
- When you do something repetitive think "there must be a better way"
- Practice what you learn

### Growing your editor

- Most editors support extensions
- When you find a limitation, look for an extension
- Build your own extensions for repetitive tasks

## Topic 19—Version control

- A Version Control System (VCS) can be a giant undo key but they can be *so* much more
- Shared directories are *not* version control

### It starts at the source

- VCSs keep track of every change
- They also answer questions:
  - Who made changes to this line of code?
  - What's the difference between the current version and last week's?
  - How may lines of code did we chanfge in this release?
  - Which files get changes most often?
- VCS also lets you identify and regenerate releases
- Two or more users can be working concurrently on the same set of files
- Always use version control, even on a team of one

### Branching out

- Branching allows you to work on code in isolation and only merge it into the main project when complete
- Branching can also be at the heart of your workflow management
- Workflow needs to suit your project; don't blindly accept another project's flow

### Version control as a project hub

- While valuable solo, version control really shines in teams
- Many VCSs do not require hosting but having a central repository offers project flow integrations
- While you could install a VCS in your compnay, third-party hosting is recommended

## Topic 20—Debugging

- The term "bug" came about after a moth was caught in an early computer system
- No one writes perfect software

### Psychology of Debugging

- Debugging can be a sensitive subject
- Embrace the fact that debugging is just problem solving, and attack it as such.
- Fix the problem, not the blame

> It doesn’t really matter whether the bug is your fault or someone else’s. It is still your problem

### A debugging mindset

- Turn off the defenses that protect your ego
- Don't panic
- If you think "that's impossible", you are plainly wrong
- Resist the urge to fix just the symptoms you see
- Discover the root cause

### Where to start

- Make sure you are working from code that builds cleanly
- Gather all the relevant data
- It's easy to be misled; be accurate in your observations
- You may need to watch the user who reported the bug to get sufficient detail

### Debugging strategies

> Once *you* think you know what's going on, it's time to find out what the *program* thinks is going on

#### Reproducing bugs

- The best way to fix a bug is to make is reproducable (preferably with a single command)
- Write a failing test before fixing code

#### Coder in a strange land

> Read the damn error message

#### Bad results

- If you get a bad result (not a crash), get in with a debugger and use the failing test to trigger the issue
- Be certain you are seeing the incorrect value in the debugger
- Take notes

#### Sensitivity to input values

- If things work in test but failed in production, try to get the dataset and reproduce locally

### The binary chop

- Use a binary chop/search when the issue is an incorrect value and you are faced with a large stacktrace
  - Start in the middle of the stacktrace
  - Check the value
  - If correct, go half way towards the end, else halfway to the start
  - Repeat
- You can also perform a binary chop on commits in version control

### Logging and/or tracing

- Debuggers focus on the state now
- When you need to see values over time, tracing statements can be valuable
- Trace messages should be in a consistent format

### Rubber ducking

- Explaining the problem to a silent third-party can cause the solution to become clear
- If you don't have a person, use a rubber duck

### Process of elimination

- It's possible that a bug exists in a third-party product but this should not be your first thought
- It's more likely the bug is in your code

### The element of surprise

- When faced with a "surprising" failure, you must accept that one of more of your assumptions is wrong
- Prove your assumptions, no matter how much you "know" it works
- Consider if you need to amend the tests so they would have caught the bug

## Topic 21—Text manipulation

- Text manipulation languages are noisy, messy, and somewhat brute force
- In the right hands, they can be incredibly powerful and versatile
- Consider tools such as awk and sed

## Topic 22—Engineering Daybooks

- Keeping a daybook of your learnings and values is beneficial because it:
  - Is more reliable than memory
  - Gives you a place to store ideas that aren't immediately relevant
  - Acts as a kind of rubber duck
- Use paper

**Comment by HashNotAdam** [comment] 2020-04-02 04:41
## Discussion notes

@HashNotAdam: How do you feel about "Tracer Bullets" as an analogy?
@mcgain: They love military analogies... which is not ideal. The metaphor doesn't work. The concept reminds of Observability, the next evolution of logging. You take all of your metrics—including what CPU is doing, memory limits, IO—and combine them with application logs and then extract useful information from it. You want to richly annotate your logs so they are machine-parsable and then you can "do all sorts of fun things". For example, trace that your slow code is coming from a particular area but what makes it better than traditional Application Performance Monitoring is that it can consider all requests across all instances across various parts of your infrastructure.

> "A talk about Observability" provided by @mcgain via the Slack discussion
> https://www.usenix.org/conference/srecon19asia/presentation/krabbe

@lachlanhardy: I @#$%ing hate war analogies for work. Business doesn't need to be combative; saying this, it is difficult to find an analogy that is equally evocative.

@HashNotAdam: When building out a product, it is extremely easy to overengineer.
@HashNotAdam: When is a good time to use a Tracer Bullet?
@lachlanhardy: Calls them "Technical Spikes" and sees them as a place to "come to grips with the domain" and/or validate that systems can actually be connected. Recently a client asked if they could start a blog inside their current site and the response was "I don't know, let's find out, give me a week". During that time, the goal wasn't to build a blog, it was just to connect enough "pieces" together to be able to say that a blog could be integrated.

@elle: Is very familiar with a Spike but has not previously heard the term "Tracer Bullet". The term "Spike" came from Extreme programming, a type of Agile programming, and yet the authors seemed to avoid mentioning Agile. While the original version of the book pre-dates the Agile Manifesto, the 20th-anniversary release discusses the authors influence upon the Agile movement while simultaneously avoiding using Agile terminology.
@mcgain: "Now we've come full circle and the term is meaningless and poison"

@HashNotAdam: Has not previously had a language for this process. This could also come from working with clients that don't appreciate the complexities of application development and expect things to be perfect in the first iteration.
@elle: Recommends using Design Sprints as a way to perform the iterative learning and build process in such a way as to bring the client on the journey and ensure their buy-in.
@HashNotAdam: Can use the pandemic as an opportunity to clear out the deadwood. "Any of those shit clients that won't come along for the ride are gone now".
Siri: I don't know how to respond to that.

@HashNotAdam: Now primarily uses Figma for design and so prototypes become a simple addition to the design process.
@elle: Regardless of your tool, Wireframes are valuable. Putting something in front of a client so they can talk about the specifics is extremely beneficial.
@lachlanhardy: It is even better when there is a person who is dedicated to building prototypes so that, as a developer, you can remain focused on the core of the project. When developers think "I can just build the prototype in my language", they get bogged down.
@HashNotAdam: Never codes a prototype; always uses tools like Figma, particularly when that is where the designs are built anyway.
@tomdalling: Or as simple as writing screens on Post-It Notes; whatever you need to do to get it done quickly.
@lachlanhardy: It does become harder when you need to show your client your wall of Post-It Notes.

@HashNotAdam: What is an acceptable time to use a Domain Language?
@tomdalling: When there is a lot of repetition. For example, if you have a lot of configurations for which you may only need a sample, a DSL can be a lot easier to read.
@mcgain: Generally they grow organically out of seeing repetition. Generally, this is valuable initially, however, as things grow, you tend to end up writing lots of exceptions. There would need to be a very strong case to want to use a DSL again.
@elle: The problem with a DSL is that you need to learn a new set of rules on top of the language. Learning both Ruby and Rspec at the same time was too much and so started with Minitest and adopted Rspec at a later date. Rspec, however, is an example of a good DSL as opposed to Cucumber.
@saramic: Reminds everyone that he is actually in the meeting by presenting the piece of cucumber he is actively devouring. Also, the place for a DSL can be when you are a consultant and you see the same problem across numerous companies. At Redbubble, there were times where a DSL could have been used for configuration but that could have resulted in the issue @mcgain faced.
@elle: If you see the same problem multiple times across a single business, that can be a good time to create a shared (Ruby) Gem. It is important to remember (as stated in the book) that it's only worth building a DSL if it is going to save you time in the long run, not because the challenge is fun.
@mcgain: Recommends the book, Domain-Specific Languages, which addresses when to use a DSL and when to use an internal vs external DSL
@HashNotAdam: Generally tries to avoid DSLs except when building libraries and felt the book made it sound like DSLs are something you should use often.

@HashNotAdam: How do feel about the concept that you should stop estimating at 20 weeks?
@elle: Thoughtbot will only estimate a project as small (up to 3 months), medium (3 to 6 months), or large (over 6 months). Having looked at a range of different ways to estimate, it is rare that an estimate is correct. The best estimate came by breaking out and estimating each feature and then doubling.
@lachlanhardy: When you are asked to estimate, the best thing you can do is find out what the estimate means to them. Help them understand that, if they want fine granularity, you essentially are just doing the work. Understand the granularity needed and estimate appropriately or find another way around the concerns.
@lachlanhardy: Using confidence intervals can be valuable for driving conversations regarding what could sway the project from one end of the range to the other. It is most important to give your client an honest understanding of reality.
@tomdalling: A confidence interval that has a large range (i.e. 4–12 months) can be tough but maybe it helps get people into discussions about where the uncertainties lie.
@elle: Finds it valuable to understand the budget and requirements and tell the client how many of the requirements can fit in the budget, explaining the idea of time, money, and quality.

@HashNotAdam: Recently was asked to quote on a project that had very few details in the brief and asked some very high-level questions to try to narrow the scope a bit. In the meantime, another company quoted based upon the vague brief and instantly won the contract. Should you accept that this was probably not the client you want or give a quote estimate that can be refined with time.
@lachlanhardy: Would prefer to provide a fast estimate using a confidence interval to start a conversation.
@tomdalling: It's best if you can convince the client to use an iterative process but it can be a very hard sell. "You want us to pay you for an unlimited amount of time‽"
@elle: You don't want a client that won't accept an iterative process but you should also sit with your client and lay out 3 buckets: must-haves; should-haves; and nice-to-haves. Often you need to sit with your client and help them understand what they actually need for a successful project.
@lachlanhardy: The way you want to frame it is "delivering value in an iterative fashion". Explain that we're not asking to be paid indefinitely, we are saying that for each agreed-upon block of time, we will deliver value equivalent to the amount being paid. "You might end up working with me for 3 years, and we might both love that, but we shouldn't budget for that now".
@elle: The challenge with iterative work based on an hourly rate is that the more times you perform a task, the less time it will take you to perform that task. This raises the question of value vs time-based pricing.

@HashNotAdam: The idea in the book that you only need to be concerned about inaccurate estimates when you miss your target by at least 50% is a scary thought.
@tomdalling: This goes back to the idea of not estimating on longer projects. If you are working iteratively on a month-to-month basis, do you even need to estimate past the current month‽
@lachlanhardy and @elle: Can't understand why Agile sprints exist and they simply provide opportunity for questions regarding why a scheduled task was not completed.

@HashNotAdam: Enjoyed *The Power of Plain Text* but has nothing to say about it
@tomdalling: It's good... that is all

@mcgain has thoughts on debugging which was not intended to be in this session but we'll allow it.
@mcgain: Had many juniors look shocked when he uses `puts` for debugging. There are "cults" that teach people that there are strict ways to do things with no concept of nuance. If you want to understand how data is changing, `puts` can be a great solution while the debugger is better for understanding flow in a single-threaded process.
@elle: Recommends a video that includes a discussion of `debugger` vs `pry`

> "Interactively Debugging Test Failures" provided by @elle via the Slack discussion
> https://thoughtbot.com/upcase/videos/interactively-debugging-test-failures

@mcgain: There are some people who say you should never use debuggers or logging to debug an issue, you should be able to understand from reading the code "and to those people, I say 'screw you'"

**Closed** 2020-04-02 04:44 UTC
Labels: pragmatic-programmer
